### ISSUE TITLE
Colouring the output in CLI of the Window platform issue

### ISSUE THREAD

**Issue by eunbeek** [badalsarkar/Blink#1]
## Issue Desc
I tested this tool in Window, using CMD, PowerShell and found this issue. Each result should be returned with colour but the applied colour code looks broken.

 
## Issue Scenario

```bash
java -jar urlchecker.jar -s urls.html
```

## Screen Shot
- CMD

![image](https://user-images.githubusercontent.com/50673489/94077661-fa6f2d80-fdcb-11ea-9c35-d16162c61b49.png)

- PowerShell

![image (1)](https://user-images.githubusercontent.com/50673489/94077731-fe9b4b00-fdcb-11ea-93a3-d4fefb4a579f.png)

## Environment
- Window OS

**Comment by badalsarkar** [comment]
I fixed the output error in the first column. Currently the application only supports colour output in Linux terminal. I am working on the colour support for windows command line.
